### PR TITLE
No need to use stateful

### PR DESCRIPTION
**Pull request by fkorotkov**
Stateful tasks with the combination of high CPU results in very long scheduling times.

### CODE REVIEW

**Comment by fkorotkov** [comment]
@Maitreya29 I've noticed that [this task](https://cirrus-ci.com/task/5056938418372608) was scheduling very long and noticed that `stateful` here was misused.

**Comment by Maitreya29** [comment]
oh thank you so much! @fkorotkov

**Comment by Maitreya29** [comment]
also wished to thank you for Cirrus. It's helping me a lot!

**Comment by fkorotkov** [comment]
@Maitreya29 glad you liked it!

Can I ask you why are building Android Open Source Project from sources that often? I've see an increased amount of similar projects and want to understand your usage better. Do you build it that often to have pre-release builds for your devices?

**Comment by fkorotkov** [comment]
Thanks for the clarification! That explains a bunch of very similar builds. 😅 Wishing you all the best with optimizing the builds. Seems now it only uses all the cores only like half a time:

Screen Shot 2021-03-25 at 2 24 57 PM

**Comment by Maitreya29** [comment]
> Thanks for the clarification! That explains a bunch of very similar builds. 😅 Wishing you all the best with optimizing the builds. Seems now it only uses all the cores only like half a time:
> 
> Screen Shot 2021-03-25 at 2 24 57 PM

Yup that's why I plan to bring it down to probably 10cores with time.

**Comment by Maitreya29** [comment]
Hello @fkorotkov I recently reduced cpu count to 10 so I believe I was succesful with the optimisation but today, I saw my repo got blocked. Would it be okay for me to ask why this happened?

**Pull request merged**
